apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/d3ceiver/argo.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: xmrig

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig
  name: xmrig
  namespace: xmrig 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xmrig
  strategy: {}
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - xmrig
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: rcmelendez/xmrig:6.16.2
        name: xmrig
        command: ["xmrig"]
        args: ["-c", "/xmrig/etc/config.json"]
        resources:
          limits:
            memory: "4Gi"
            cpu: "4"
          requests:
            memory: "2Gi"
            cpu: "2"      
        volumeMounts:
        - name: config-volume
          mountPath: /xmrig/etc
      volumes:
      - name: config-volume
        configMap:
          name: xmrig-config
         
